name: Deploy Cloud Functions

on:
  push:
    branches:
      - dev
      - master

jobs:
  deploy:
    name: Deploy Cloud Functions
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 4: Set up Service Account for Firebase
      - name: Set up Service Account
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json

      # Step 5: Install dependencies
      - name: Install dependencies
        working-directory: ./functions
        run: npm install

      # Step 6: Deploy to Firebase
      - name: Deploy Cloud Functions
        working-directory: ./functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          firebase deploy --only functions --non-interactive
